#!/usr/bin/env ts-node
/**
 * E2E pre-setup script — run once before the first test run (or in CI).
 *
 * Creates a persistent Bridge test app for E2E tests and writes the resulting
 * BRIDGE_TEST_APP_ID into e2e/config/.env.test.local so that Jest picks it up
 * automatically via setupFiles.
 *
 * Usage:
 *   npm run e2e:setup
 *
 * The test app persists across runs (idempotent). Re-running this script is
 * safe — it returns the existing app if the domain already exists.
 *
 * Required environment variables (set in your shell or CI):
 *   PLAYWRIGHT_TEST_API_KEY — API key for the Bridge test data service
 *
 * Optional:
 *   APP_DOMAIN              — unique domain for the test app (default: BRIDGE_NESTJS_E2E_TEST)
 *   LOCAL_TEST_DATA_API_URL — override bridge-api URL (default: http://localhost:3200)
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { TEST_APP_URL } from './config/test-app';

// Load existing .env.test.local (if any) so we don't clobber other vars
const envFilePath = path.join(__dirname, 'config', '.env.test.local');
if (fs.existsSync(envFilePath)) {
  dotenv.config({ path: envFilePath });
}

const TEST_DATA_API_URL =
  process.env.LOCAL_TEST_DATA_API_URL || 'http://localhost:3200';
const PLAYWRIGHT_TEST_API_KEY = process.env.PLAYWRIGHT_TEST_API_KEY;
const APP_DOMAIN =
  process.env.APP_DOMAIN || 'BRIDGE_NESTJS_E2E_TEST';

if (!PLAYWRIGHT_TEST_API_KEY) {
  console.error(
    '❌ PLAYWRIGHT_TEST_API_KEY is not set.\n' +
      'Export it in your shell or add it to e2e/config/.env.test.local.',
  );
  process.exit(1);
}

async function main() {
  console.log('🔧 bridge-nestjs E2E pre-setup');
  console.log(`   Test data API: ${TEST_DATA_API_URL}`);
  console.log(`   App domain:    ${APP_DOMAIN}`);

  // ── Health check ────────────────────────────────────────────────────────
  console.log('\n[1/2] Checking test data API health…');
  const healthResp = await fetch(
    `${TEST_DATA_API_URL}/account/test/playwright/health`,
    { headers: { 'x-playwright-api-key': PLAYWRIGHT_TEST_API_KEY! } },
  );
  if (!healthResp.ok) {
    console.error(
      `❌ Test data API health check failed: ${healthResp.status}`,
    );
    process.exit(1);
  }
  console.log('   ✅ API reachable');

  // ── Create / retrieve test app ───────────────────────────────────────────
  console.log('\n[2/2] Setting up test app (idempotent)…');
  const setupResp = await fetch(
    `${TEST_DATA_API_URL}/account/test/playwright/setup-test-app`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-playwright-api-key': PLAYWRIGHT_TEST_API_KEY!,
      },
      body: JSON.stringify({
        domain: APP_DOMAIN,
        appName: 'bridge-nestjs E2E Test App',
        ownerEmail: `bridge-nestjs-e2e-owner@thebridge.io`,
        ownerPassword: 'helloworld',
        appUrl: TEST_APP_URL,
      }),
    },
  );

  if (!setupResp.ok) {
    const body = await setupResp.text();
    console.error(`❌ setupTestApp failed: ${setupResp.status} ${body}`);
    process.exit(1);
  }

  const app = (await setupResp.json()) as {
    appId: string;
    domain: string;
    message: string;
  };
  console.log(`   ✅ ${app.message}`);
  console.log(`   App ID: ${app.appId}`);

  // ── Write env file ───────────────────────────────────────────────────────
  const envLines = [
    `# Generated by e2e/pre-setup.ts — do not edit manually`,
    `BRIDGE_TEST_APP_ID=${app.appId}`,
    `APP_DOMAIN=${APP_DOMAIN}`,
    `PLAYWRIGHT_TEST_API_KEY=${PLAYWRIGHT_TEST_API_KEY}`,
  ];

  // Preserve optional URL overrides from existing file
  const existingVars = ['LOCAL_AUTH_BASE_URL', 'LOCAL_TEST_DATA_API_URL'];
  for (const varName of existingVars) {
    const val = process.env[varName];
    if (val) envLines.push(`${varName}=${val}`);
  }

  fs.writeFileSync(envFilePath, envLines.join('\n') + '\n', 'utf8');
  console.log(`\n✅ Wrote ${envFilePath}`);
  console.log('\nYou can now run: npm run e2e:test');
}

main().catch((err) => {
  console.error('❌ pre-setup failed:', err);
  process.exit(1);
});
